// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATS9AVa285pYea0C_FN5sD8MHCmOlo4e0',
    appId: '1:974302830503:web:85a98b103fc37f41da6082',
    messagingSenderId: '974302830503',
    projectId: 'sailordou',
    authDomain: 'sailordou.firebaseapp.com',
    storageBucket: 'sailordou.appspot.com',
    measurementId: 'G-FN4QH630GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIiXzg12VuRpcSvjgd0px-2Uu47TOMOGo',
    appId: '1:974302830503:android:49785798bc0608dfda6082',
    messagingSenderId: '974302830503',
    projectId: 'sailordou',
    storageBucket: 'sailordou.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS68wYxPgLD8mfiWze5ADkQRoX-3UY6PE',
    appId: '1:974302830503:ios:d3b48d699eb1109ada6082',
    messagingSenderId: '974302830503',
    projectId: 'sailordou',
    storageBucket: 'sailordou.appspot.com',
    iosBundleId: 'com.example.sailordou',
  );
}
